# Generated by Django 4.1.6 on 2023-03-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('store_name', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=13)),
                ('product_name', models.CharField(max_length=1000)),
                ('type_of_product', models.CharField(max_length=2000)),
                ('product_quality', models.CharField(max_length=1000)),
                ('precious_metal', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10000)),
                ('pure_rate', models.CharField(max_length=10000)),
            ],
        ),
    ]
