# Generated by Django 4.1.6 on 2023-03-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelapp', '0004_dealer_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='selDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=1000)),
                ('sstore_name', models.CharField(max_length=1000)),
                ('scommuni', models.CharField(max_length=20)),
                ('sproduct_name', models.CharField(max_length=1000)),
                ('stype_of_product', models.CharField(max_length=2000)),
            ],
        ),
    ]
