# Generated by Django 3.2.18 on 2023-03-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelapp', '0005_seldealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='contact',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='seldealer',
            name='scommuni',
            field=models.CharField(max_length=2000),
        ),
    ]
